### ISSUE TITLE
Funnel not showing correct % changes based on initial stage

### ISSUE THREAD

**Issue by gprashmi** [mckn/mckn-funnel-panel#18]
@mckn I have developed a visualization using the Funnel Plugin in Grafana. I use SQL query to fetch the data and transform Row to Fields to have one column per field. The funnel gets displayed, however the last stage of the funnel is not shown as a block and also the % change column generated (on the right side) is not calculated correctly. Can you please let me know if I can edit the % through a code/ query since I see I cannot make changes to the funnel data displayed.

**Comment by gprashmi** [comment]
Solved it based on the comment by @geckogecko.

**Comment by mckn** [comment]
Closing this issue since it seems to be resolved by #17
