### ISSUE TITLE
Enhancement: Allow font color and size control

### ISSUE THREAD

**Issue by psheehymn** [mckn/mckn-funnel-panel#19]
First, thank you for building this plugin; we've been doing half-baked, kludgy funnel charts using the Bar Chart visualization, so this has really improved what we are able to display. 

It appears the font color on the plugin is currently dictated by the selected UI Theme (light or dark). While that works great for the description and the overall percentage in the left and right columns, the font on the funnel itself is impacted by the funnel color and we've heard readability issues from users in both camps. We are doing monochromatic funnels on purpose, with both a current time range and a comparative time range (typically same time range, prior week) and we use lighter and darker shades of the same color on the comparative funnels to differentiate the two.

On light colors, the white font in dark mode can be difficult to read and ditto for dark colors in light mode. Here are two examples:
![Light](https://github.com/mckn/mckn-funnel-panel/assets/93273674/1a68f05d-ddf4-414f-b260-cd2a9fb3bcd8)
![Dark](https://github.com/mckn/mckn-funnel-panel/assets/93273674/1ff9281d-adf2-4fe2-8322-0f3c6b80c0f1)

If possible, it would be nice to have a "funnel font color" option to allow the panel developer to select the optimal font color (even if just between white and black) to contrast best with the the funnel color.

**Comment by psheehymn** [comment]
In addition, we've run into a situation where having at least rudimentary control of the font size would also be beneficial. In developing a requested report which does a week-over-week comparison for four weeks, we've run into a situation where the numbers in the funnel are being cut off in some cases:
![image](https://github.com/mckn/mckn-funnel-panel/assets/93273674/d65ce752-1ce7-44b8-843b-d55c9a0d465c)
![image](https://github.com/mckn/mckn-funnel-panel/assets/93273674/b511f11d-df40-4302-9494-e979367ba219)

It would be nice to either have either a small/medium/large size option or the ability to set the font pixel value like with Stat visualization.

**Comment by mckn** [comment]
I can add an option where you can set font size and color. Then you can use the field overrides to control it for each step (if needed to be controlled individually).

**Comment by mckn** [comment]
I will close this issue based on PR #29 and #33. I'm also planning on improving the smartness of the width of the bars so the smallest bar will have a minimum width and all others will be calculated relative to that one.

**Comment by psheehymn** [comment]
Has this enhancement been released yet? I just downloaded 1.1.1 and don't see options for the font size and text color and the numbers on the narrow entries are still truncated.

**Comment by mckn** [comment]
No, not the possibility to set the font size manually. I was thinking on trying to do this automatically to keep the settings simple. Can you share a screenshot for how it behaves for you?

**Comment by psheehymn** [comment]
> No, not the possibility to set the font size manually. I was thinking on trying to do this automatically to keep the settings simple. Can you share a screenshot for how it behaves for you?

Please see the **March 20** entry above.

**Comment by mckn** [comment]
> > No, not the possibility to set the font size manually. I was thinking on trying to do this automatically to keep the settings simple. Can you share a screenshot for how it behaves for you?
> 
> Please see the **March 20** entry above.

That should be fixed in the `v1.1.1` release.
