### ISSUE TITLE
Data persistence issue

### ISSUE THREAD

**Issue by LiranPo** [mckn/mckn-funnel-panel#20]
I am encountering a recurring issue with the funnel chart, where data seems to "linger" when changing the dashboard's parameters (or when hitting the "refresh" button). Here are the details:

**Environment**:
Grafana version: 10.4.2
Browser: Chrome and Safari (Issue reproduced in both)

**Steps to Reproduce**:

1. Select initial parameters on the dashboard and generate the funnel chart.
2. Change the parameters to new values.
3. Observe that the values from the initial run persist and are stacked on the results of the second run (see attached screenshot).

The funnel chart retains (some of the) data from the first run and combines it with data from the second run. 
The only way to clear the data and start fresh is to refresh the entire page. Clicking the "refresh dashboard" button does not resolve the issue.

The screenshot below shows for example the "limit_results" step that is stacked over and over again. So much so, that the funnel even covers the visualization below...

![Screenshot 2024-06-27 at 19 52 27](https://github.com/mckn/mckn-funnel-panel/assets/37546907/166bb8bc-1d3e-44dc-99da-1e069a96f442)

**Comment by jasonlanderson** [comment]
I'm having this same issue.  It seems like it's duplicating or readding steps on panel refresh without clearing the existing data. This happens specifically when I change the dashboard parameters.

**Comment by mckn** [comment]
Thanks for opening this issue! I will try to reproduce this during the day and open a fix prior to the next release.

**Comment by jasonlanderson** [comment]
Thanks @mckn, let me know if you need any help!

**Comment by mckn** [comment]
I think it has do to with the generated key for each component which makes it append instead of re-rendering the bar. Trying to verify it aws.

**Comment by mckn** [comment]
@jasonlanderson can you please provide some test information? Can you share anything regarding your dashboard that can help me reproduce this?

**Comment by mckn** [comment]
I think I managed to reproduce it and have a fix in #32

**Comment by jasonlanderson** [comment]
Awesome, thanks @mckn!  Is there an easy way I can update the funnel plugin in our grafana instance to test it out?  We used `grafana-cli plugins install mckn-funnel-panel` originally to install it.

**Comment by LiranPo** [comment]
Would also appreciate guidance on how to update.
We use `grafana-cli --pluginUrl https://github.com/mckn/mckn-funnel-panel/releases/download/v1.0.0/mckn-funnel-panel-1.0.0.zip plugins install mckn-funnel-panel`
