### ISSUE TITLE
Unable to see the Last Level of the funnel when using a Qury like "select  52300 'Sent',35679 'Viewed' , 15690 'Clicked', 5596 'Add to cart', 3290 'Purchased' "

### ISSUE THREAD

**Issue by budaumarius** [mckn/mckn-funnel-panel#39]

**Comment by budaumarius** [comment]
Can you Provide better decription on how to use this funnel and query we should use ?

**Comment by budaumarius** [comment]
We are usinh Grafana 11 and the output looks like this 
![Untitled](https://github.com/user-attachments/assets/1c74ea12-3562-4723-87e8-c1af6c5a3834)

**Comment by budaumarius** [comment]
As you can see the last level Purchased is not displayed

**Comment by mckn** [comment]
oh, let me have a look at that. Looks like your data is correct but the visualisation is off. Thanks for opening this issue and providing lots of information to reproduce it.

**Comment by mckn** [comment]
Should be fixed in next version.

https://github.com/mckn/mckn-funnel-panel/pull/37
