### ISSUE TITLE
Font color issues on thin segments and percentage questions

### ISSUE THREAD

**Issue by psheehymn** [mckn/mckn-funnel-panel#40]
This issue partially relates to issue# [19](https://github.com/mckn/mckn-funnel-panel/issues/19).

![Funnel1](https://github.com/user-attachments/assets/909b217a-536d-481f-89c6-b5366809ab8f)

The attached screen capture illustrates the same funnel duplicated with three different color schemes. Because of the width of the lower tiers of the funnel, some of the numbers disappear due to the automatic font colors. Can the plugin detect the background mode selection (light or dark) and if the width of the funnel tier is very narrow, select the font color that will contrast best with the background, rather than the color of the funnel tier?

We also have concerns with the percentages being calculated and shown on the funnel; the percentage numbers don't seem correct. The text box below the three funnels illustrates what we expect the percentages to be, unless there is some aspect of a funnel diagram we do not understanding.

**Comment by psheehymn** [comment]
I forgot to mention, this is using Grafana 10.4 and version 1.1.1 of the plugin.

**Comment by mckn** [comment]
Thanks for the issue. I will try to get a fix out for this on Friday this week.

**Comment by mckn** [comment]
Fixed by https://github.com/mckn/mckn-funnel-panel/pull/37
