### ISSUE TITLE
Feature : disable automatic sorting

### ISSUE THREAD

**Issue by burn1ngd0g** [mckn/mckn-funnel-panel#44]
I created a PR to disable sorting using a panel switch option : https://github.com/mckn/mckn-funnel-panel/pull/43

Allows to use funnel in some fancy way like presenting it upside down

**Comment by mckn** [comment]
Closed by https://github.com/mckn/mckn-funnel-panel/pull/43

**Comment by burn1ngd0g** [comment]
Hello,

the release was not built due to issue pulling a grafana image during tests.

Is there a way to retry the CI?

thanks

**Comment by mckn** [comment]
Yeah, I will have a look at this tomorrow morning.
